import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/": [
    {
      text: "必看",
      icon: "star",
      prefix: "star/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "面试准备",
      icon: "book",
      prefix: "interview/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "每天重要知识点",
      icon: "bell",
      prefix: "knowledge-point-per-day/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Java",
      icon: "coffee",
      prefix: "Java/",
      collapsible: true,
      children: "structure",
      // children: [
      //   "",
      //   "java-basic01" ,
      //   "java-basic02" ,
      // ],
    },
    {
      text: "数据库",
      icon: "database",
      prefix: "database/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "计算机基础",
      icon: "computer",
      prefix: "computer/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "开发工具",
      icon: "wrench",
      prefix: "tools/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "常用框架",
      icon: "paper-plane",
      prefix: "framework/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "微服务",
      icon: "leaf",
      prefix: "service/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "分布式",
      icon: "sitemap",
      prefix: "distributed/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "项目",
      icon: "fish",
      prefix: "project/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "前端技术",
      icon: "thumbtack",
      prefix: "front/",
      collapsible: true,
      children: "structure",
    },
    // "slides",
  ],
});
